[target.thumbv8m.main-none-eabihf]
#runner = 'probe-rs run --chip STM32H503RBTx'
runner = 'probe-run --chip STM32H503RBTx  --shorten-paths'

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "trace"
